### ISSUE TITLE
Feature: User can set up a company profile

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click the profile icon located in the bottom right corner of the app. After clicking, the user will be taken to 
a page with a form where they can enter their company name. They can save the changes or click the arrow to go back to the 
main page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/220480041-406bbe90-5018-4aba-b8a9-5ba40fb781c2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Add users table
- [ ] Add appropriate data columns

### ☁️ Server Tasks

- [ ] create query to store company name for the user in the users table

### ⚡ Client Tasks

- [ ] Create a component to gather profile information
- [ ] Update component to gather the company name from the form and insert into database

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
