### ISSUE TITLE
Feature: User can categorize revenue entry

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When making an entry for revenue the user one of the options on the form is to choose the category. The user can also click the '+' symbol next to the category drop down menu to add or remove a category. Once the user clicks the '+' symbol they will be taken to the categories page where they can see a table of current categories and where they can enter a new category in the form and click save.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/220481730-36991bc9-92e6-43c9-96a4-7538c41c4d4d.png)

![image](https://user-images.githubusercontent.com/53235890/220481762-b47c71b0-e3ef-4878-a265-435e80f5c3ea.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
